In [ ]:
# Label encoding
from sklearn.preprocessing import LabelEncoder

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

# LabelEncoder를 객체로 생성한 후, fit()과 transform()으로 레이블 인코딩 수행
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환값:', labels)
print('인코딩 클래스:', encoder.classes_)
print('디코딩 원본값:', encoder.inverse_transform(labels))

인코딩 변환값: [0 1 4 5 3 3 2 2]
인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']
디코딩 원본값: ['TV' '냉장고' '전자레인지' '컴퓨터' '선풍기' '선풍기' '믹서' '믹서']


In [ ]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

# 원-핫 인코딩을 위해서는 숫자 값이 들어가야 하므로, LabelEncoder로 변환함
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

# 2차원 데이터로 변환
labels = labels.reshape(-1,1)
print(labels)
print('------------ 원-핫 인코딩 데이터 ---------------')

#원-핫 인코딩 적용
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
print(oh_labels.toarray())
print(oh_labels.shape)

[[0]
 [1]
 [4]
 [5]
 [3]
 [3]
 [2]
 [2]]
------------ 원-핫 인코딩 데이터 ---------------
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
(8, 6)


In [ ]:
# 판다스를 통한 원-핫 인코딩
import pandas as pd
df = pd.DataFrame({'items' : ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']})
pd.get_dummies(df)

items_TV  items_냉장고  items_믹서  items_선풍기  items_전자레인지  items_컴퓨터
0         1          0         0          0            0          0
1         0          1         0          0            0          0
2         0          0         0          0            1          0
3         0          0         0          0            0          1
4         0          0         0          1            0          0
5         0          0         0          1            0          0
6         0          0         1          0            0          0
7         0          0         1          0            0          0

In [ ]:
from sklearn.datasets import load_iris
import pandas as pd

# 피처 스케일링 -> 표준화, 정규화
# StandardScaler: 표준화 지원(개별 피처를 평균이 0이고 분산이 1인 값으로 변환)
from sklearn.preprocessing import StandardScaler

iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns = iris.feature_names)

# StandardScaler 객체 생성
scaler = StandardScaler()
# StandardScaler로 데이터 세트 변환
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

# transform()을 통해 스케일 변환된 데이터 세트가
# Numpy ndarray로 반환되었으므로, 이를 다시 변환
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns = iris.feature_names)
print(iris_df_scaled.head())

# 평균이 0, 분산이 1에 가까운 값으로 변환되었음
print(iris_df_scaled.mean())
print(iris_df_scaled.var())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0          -0.900681          1.019004          -1.340227         -1.315444
1          -1.143017         -0.131979          -1.340227         -1.315444
2          -1.385353          0.328414          -1.397064         -1.315444
3          -1.506521          0.098217          -1.283389         -1.315444
4          -1.021849          1.249201          -1.340227         -1.315444
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


In [ ]:
# MinMaxScaler는 데이터를 0과 1사이의 값으로 변환하는데,
# 데이터의 분포가 가우시안 분포가 아닐경우에 적용할 수 있음
from sklearn.preprocessing import MinMaxScaler

# MinMaxScaler 객체 생성
scaler= MinMaxScaler()

# MinMaxScaler로 데이터 세트 변환. fit, transform 호출
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

# transform()을 통해 스케일 변환된 데이터 세트가
# Numpy ndarray로 반환되었으므로, 이를 다시 변환
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns = iris.feature_names)
print(iris_df_scaled.head())

print(iris_df_scaled.min())
print(iris_df_scaled.max())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0           0.222222          0.625000           0.067797          0.041667
1           0.166667          0.416667           0.067797          0.041667
2           0.111111          0.500000           0.050847          0.041667
3           0.083333          0.458333           0.084746          0.041667
4           0.194444          0.666667           0.067797          0.041667
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


In [ ]:
# 단, 스케일링을 했을 때 학습용 데이터와 테스트 데이터가 동일한 기준을 가지고 있어야함
# 따라서 전체 데이터 스케일링 -> 학습 및 테스트 데이터 분리
# 혹은, 학습 데이터에서 사용한 fit()을 그대로 테스트 데이터에서 사용